### ISSUE TITLE
Funds never arrived on DFI Wallet

### ISSUE THREAD

**Issue by DEFICHAINFAN** [muirglacier/bridge-ui#23]
Hello guys,

I was using the BSC https://defichain-bridge.com/ Bridge today, one of my transactions went fine but the other one got stuck, I was trying to send funds to a Defichain wallet, the funds never arrived on Defichain' wallet.

I tried using the recovery option but I get this error message after entering the transaction ID:
"Broadcasted raw tx: undefined"

The BSC transaction ID is the following one : 0x86a76240caddd685c6ab13f6f2953148ed9b41fe4533b557abb6c9d149607530

The wallet where I was expecting the funds: dKTyfd2jcKib8WUFTo318ruTf7nHUtWZ9M

The transaction seems to have worked fine until they were burnt on Binance though: https://bscscan.com/tx/0x86a76240caddd685c6ab13f6f2953148ed9b41fe4533b557abb6c9d149607530

Thank you for your help.

**Comment by muirglacier** [comment]
Looking into it now for you

Sent from my iPhone

On 30 Apr 2022, at 12:03 pm, DEFICHAINFAN ***@***.***> wrote:

﻿

Hello guys,

I was using the BSC https://defichain-bridge.com/ Bridge today, one of my transactions went fine but the other one got stuck, I was trying to send funds to a Defichain wallet, the funds never arrived on Defichain' wallet.

I tried using the recovery option but I get this error message after entering the transaction ID:
"Broadcasted raw tx: undefined"

The BSC transaction ID is the following one : 0x86a76240caddd685c6ab13f6f2953148ed9b41fe4533b557abb6c9d149607530

The wallet where I was expecting the funds: dKTyfd2jcKib8WUFTo318ruTf7nHUtWZ9M

The transaction seems to have worked fine until they were burnt on Binance though: https://bscscan.com/tx/0x86a76240caddd685c6ab13f6f2953148ed9b41fe4533b557abb6c9d149607530

**Comment by DEFICHAINFAN** [comment]
Thank you muirglacier. I forgot to mention that as in the case of this gentleman [17](https://github.com/muirglacier/bridge-ui/issues/17) I got this error message: 
![image](https://user-images.githubusercontent.com/104662115/166088171-6ec76953-5d45-45d4-9e17-e15b427d14e2.png)
Even though, the transaction does appear on the bscscan.

**Comment by muirglacier** [comment]
We will have it sorted for you by tomorrow!
Thanks for being part that early on, and helping to fix all the little issues!

By the way, you get a bug bounty because your funds got stuck and are not recoverable with the recovery function 🔥🔥

Sent from my iPhone

On 30 Apr 2022, at 1:07 pm, DEFICHAINFAN ***@***.***> wrote:

﻿

Thank you muirglacier. I forgot to mention that as in the case of this gentleman 17<https://github.com/muirglacier/bridge-ui/issues/17> I got this error message:
[image]<https://user-images.githubusercontent.com/104662115/166088171-6ec76953-5d45-45d4-9e17-e15b427d14e2.png>
Even though, the transaction does appear on the bscscan.

**Comment by DEFICHAINFAN** [comment]
Thank you my friend! Love the project and I did spend some time playing with it today! Was great and ended up in a really productive way for all! I'm glad!

**Comment by DEFICHAINFAN** [comment]
Hi muirglacier,

On which address should I expect my DFI and bounty please? Dfi or Metamask?
(0x3EEeA69ae13b598ff536Eb857c1142700e353d1e)
So far I didn't receive anything.

**Comment by muirglacier** [comment]
Will be sorted today! I was at a wedding on Sunday. Back to work later today

Sent from my iPhone

On 1 May 2022, at 6:57 am, DEFICHAINFAN ***@***.***> wrote:

﻿

Hi muirglacier,

On which address should I expect my DFI and bounty please? Dfi or Metamask?
(0x3EEeA69ae13b598ff536Eb857c1142700e353d1e)
So far I didn't receive anything.

**Comment by DEFICHAINFAN** [comment]
Cool thanks!

**Comment by muirglacier** [comment]
Hmm, that is weird. I have simply used the recovery function and the funds were sent without any problem.
https://defiscan.live/transactions/737b0b100678a8886ac608d51ff9f0864754293c3bc876ee93d426cb3d2bb307

Can you maybe reproduce it somehow?

**Comment by DEFICHAINFAN** [comment]
Interesting, I will try to reproduce it, in fact I tried using the recovery form many times but I got each time the error message I indicated above. 
![image](https://user-images.githubusercontent.com/104662115/166133158-031c33e0-67a6-41a3-9ce5-7b6d2f33564a.png)

**Comment by muirglacier** [comment]
The other guy tried to put in the defichain deposit tx into the release recovery field - so that Naturally didn’t work!

Added a better error message now, let’s see

Sent from my iPhone

On 1 May 2022, at 3:12 pm, DEFICHAINFAN ***@***.***> wrote:

﻿

Interesting, I will try to reproduce it, in fact I tried using the recovery form many times but I got each time the error message I indicated above.
[image]<https://user-images.githubusercontent.com/104662115/166133158-031c33e0-67a6-41a3-9ce5-7b6d2f33564a.png>

**Comment by DEFICHAINFAN** [comment]
In my case as you can see in the screenshot above, I put the Binance TxID and got that error message.
