### ISSUE TITLE
Mint on BSC Failing

### ISSUE THREAD

**Issue by Defianer** [muirglacier/bridge-ui#88]
Edit: My stuck Tx is resolved in the meantime, thanks.

**Comment by stn021** [comment]
Same here , just the other way, BSC to DFI.
"Cannot be minted on defichain" :

0xc45e345fb602f875baeadad41dba42f9e4d040ba5e31c519c3b1cfccca2ed77b
0xfff613bf62c12b903623d8ca7c1c0e2c1a5fe6a937b273005c9cf775cb85f52a

TIA, stn

**Comment by stn021** [comment]
And yet two more:
0x31cf41a6d53d0218edcd6530ea10f271f8173f2bee6595e3e5120456ab70a7cc
0xb9f3e08532140c347295eac8f11010cd702db23c0f6d26204e4289610f396de6

Many transactions work, but this one did not, for no apparent reason.
Also it cannot be recovered. The same error keeps appearing.

**Comment by Stonygan** [comment]
Do you use v1 or v2 Bridge?

**Comment by stn021** [comment]
I open https://defichain-bridge.com and use whatever comes up.
Probably the newest but I cannot be sure.

**Comment by stn021** [comment]
If you want to reproduce the error:

make a series of transactions from BSC to DFI.
Each one with a small amount, like 0.1 DFI.
Simply do one TX after the other, no pause. Most work but in between some fail, even though every click was the same on each attempt. Approximately one in 10 fails.

The problem is not that a tx may fail. 
That would be fine were it not for the fact that these failed tx cannot be recovered. If you try recover the same error comes again, even if other transactions AFTER the failed one were successfull.

So, that is what "stuck" is intended to mean.
